
export const INSTITUTES = [
    "Parul Institute of Technology",
    "Ahmedabad Homoeopathic Medical College",
    "Ahmedabad Physiotherapy College",
    "College of Agriculture",
    "Department of Paramedical & Health Sciences",
    "Faculty of Library & Information Science",
    "Institute of Pharmaceutical Sciences",
    "Jawaharlal Nehru Homoeopathic Medical College",
    "Parul College of Pharmacy & Research",
    "Parul Institute of Applied Sciences (Ahmedabad Campus)",
    "Parul Institute of Applied Sciences (Vadodara Campus)",
    "Parul Institute of Architecture & Research",
    "Parul Institute of Arts",
    "Parul Institute of Ayurveda",
    "Parul Institute of Ayurveda & Research",
    "Parul Institute of Business Administration",
    "Parul Institute of Commerce",
    "Parul Institute of Computer Application",
    "Parul Institute of Design",
    "Parul Institute of Engineering & Technology",
    "Parul Institute of Engineering & Technology (Diploma Studies)",
    "Parul Institute of Fine Arts",
    "Parul Institute of Homeopathy & Research",
    "Parul Institute of Hotel Management & Catering Technology",
    "Parul Institute of Law",
    "Parul Institute of Management",
    "Parul Institute of Management & Research",
    "Parul Institute of Medical Sciences & Research",
    "Parul Institute of Nursing",
    "Parul Institute of Performing Arts",
    "Parul Institute of Pharmaceutical Education & Research",
    "Parul Institute of Pharmacy",
    "Parul Institute of Pharmacy & Research",
    "Parul Institute of Physiotherapy",
    "Parul Institute of Physiotherapy and Research",
    "Parul Institute of Social Work",
    "Parul Institute of Vocational Education",
    "Parul Medical Institute & Hospital",
    "Parul Polytechnic Institute",
    "Parul Institute of Public Health",
    "Parul Sevashram Hospital",
    "Rajkot Homoeopathic Medical College",
    "RDC",
    "School of Pharmacy",
];

export const CRO_EMAILS: string[] = [
    'unnati.joshi22950@paruluniversity.ac.in',
    'prasanna.mathad86177@paruluniversity.ac.in',
    'ashaben.patel@paruluniversity.ac.in',
    'sheetal.thomas40536@paruluniversity.ac.in',
    'anupam.jyoti30554@paruluniversity.ac.in',
    'richa.mishra31240@paruluniversity.ac.in',
    'ankita.priyadarshini85053@paruluniversity.ac.in',
    'neha.shah40426@paruluniversity.ac.in',
];
