import type React from "react"
import type { Metadata } from "next"
import { cn } from "@/lib/utils"
import "./globals.css"
import { Inter } from "next/font/google"
import { IBM_Plex_Mono } from "next/font/google"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })
const ibmMono = IBM_Plex_Mono({ subsets: ["latin"], variable: "--font-mono" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.variable, ibmMono.variable)}>
        {children}
      </body>
    </html>
  )
}
